# Generated by Django 4.1.7 on 2023-04-08 07:23

import account.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendresume',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[account.validator.validate_resume_size]),
        ),
    ]
