# Generated by Django 4.1.7 on 2023-04-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobcategory_class_icon'),
        ('resume', '0002_alter_sendresume_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendresume',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
