# Generated by Django 4.1.7 on 2023-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_sendresume_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendresume',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
