# Generated by Django 4.1.3 on 2023-02-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ostan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('گیلان', 'گیلان'), ('مازندران', 'مازندران'), ('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('کرمانشاه', 'کرمانشاه'), ('خوزستان', 'خوزستان'), ('فارس', 'فارس'), ('کرمان', 'کرمان'), ('خراسان', 'خراسان'), ('اصفهان', 'اصفهان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('کردستان', 'کردستان'), ('همدان', 'همدان'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('لرستان', 'لرستان'), ('ایلام', 'ایلام'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('بوشهر', 'بوشهر'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('یزد', 'یزد'), ('هرمزگان', 'هرمزگان'), ('تهران', 'تهران'), ('اردبیل', 'اردبیل'), ('قم', 'قم'), ('قزوین', 'قزوین'), ('گلستان', 'گلستان'), ('خراسان شمالی', 'خراسان شمالی'), ('خراسان جنوبی', 'خراسان جنوبی'), ('البرز', 'البرز'), ('مرکزی', 'مرکزی')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('style', models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('کارآموز', 'کارآموز'), ('فریلنسر', 'فریلنسر')], max_length=20)),
                ('experience', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('salary', models.CharField(help_text='به میلیون بنویسید', max_length=3)),
                ('info', models.TextField()),
                ('necessary', models.TextField(verbose_name='مهارت های ضروری')),
                ('privilege', models.TextField(blank=True, null=True, verbose_name='مهارت های امتیازی')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobcategory')),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.ostan')),
            ],
        ),
    ]
