# Generated by Django 4.1.3 on 2023-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='telecommuting',
            field=models.BooleanField(default=False, verbose_name='امکان دورکاری'),
        ),
    ]
