# Generated by Django 4.1.7 on 2023-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_keys',
            field=models.ManyToManyField(to='job.key'),
        ),
    ]
