# Generated by Django 4.1.3 on 2023-03-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZirAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('zir_title', models.TextField()),
                ('button_name', models.CharField(max_length=150)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
