# Generated by Django 4.1.3 on 2023-03-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ziraboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
