# Generated by Django 4.1.3 on 2023-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutus_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziraboutus',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
