# Generated by Django 4.1.3 on 2023-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contatctus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('comment', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
