# Generated by Django 4.1.3 on 2023-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.TextField(blank=True, help_text='آدرس شرکت'),
        ),
    ]
