# Generated by Django 4.1.3 on 2023-02-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_company_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code_posty',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
