# Generated by Django 4.1.3 on 2023-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_company_code_posty'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='telegram',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
