# Generated by Django 4.1.3 on 2023-02-22 11:35

import account.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='')),
                ('lastname', models.CharField(max_length=250)),
                ('job', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('code_posty', models.CharField(max_length=10)),
                ('address', models.TextField(help_text='آدرس دقیق')),
                ('tahsilat', models.CharField(max_length=400)),
                ('info', models.TextField()),
                ('cv_file', models.FileField(upload_to='', validators=[account.validator.validate_file_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
