# Generated by Django 4.1.3 on 2023-02-23 06:36

import account.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[account.validator.validate_picture_size]),
        ),
    ]
