# Generated by Django 4.1.3 on 2023-03-08 15:05

import account.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_telecommuting'),
        ('account', '0012_userprofile_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cv_file',
            field=models.FileField(null=True, upload_to='', validators=[account.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wish_list',
            field=models.ManyToManyField(blank=True, to='job.job'),
        ),
    ]
