# Generated by Django 4.1.3 on 2023-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_userprofile_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Token',
            field=models.IntegerField(null=True),
        ),
    ]
