# Generated by Django 4.1.3 on 2023-03-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
