# Generated by Django 4.1.7 on 2023-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_key'),
        ('account', '0015_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='key',
            field=models.ManyToManyField(to='job.key'),
        ),
    ]
