# Generated by Django 4.1.7 on 2023-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_userprofile_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
